services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: elearning_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    image: 631640527929.dkr.ecr.eu-west-2.amazonaws.com/4all/backend:latest
    ports:
      - "8080:8080"
    environment:
      POSTGRES_URL: "postgresql://admin:admin@postgres:5432/elearning_db"
      PRIVATE_KEY: "secretbutitsuperdupersecret"
      NEXT_PUBLIC_FRONTEND_ORIGIN: "localhost:8080"
    depends_on:
      - redis
      - postgres

volumes:
  pgdata:
