import type { Metadata } from "next";
import "@/app/ui/globals.css";
import { inter } from "@/app/ui/fonts";
import SideNav from "./ui/sidenav";

export const metadata: Metadata = {
  title: "4all",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <SideNav />
        {children}
      </body>
    </html>
  );
}
