# Step 1: Use an official Node.js image as a base
FROM node:22-alpine3.19

# Step 3: Copy the package.json and package-lock.json (for npm) or yarn.lock (for yarn)
COPY package*.json ./

# Step 4: Install the dependencies
RUN npm install
# Step 5: Copy the rest of the application code
COPY . .

# Step 6: Expose the port your application will run on
EXPOSE 80

# Define the command to run your app
CMD [ "npm", "run", "migrate" ]